spring:
  application:
    name: trypostgresql
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/mydatabase}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword}

server:
  port: ${SERVER_PORT:8081}
